package types

var MySQLTypeMap = map[string]DbType{
	"varchar":    String,
	"char":       Char,
	"text":       String,
	"tinytext":   String,
	"mediumtext": String,
	"longtext":   String,
	"int":        Integer,
	"integer":    Integer,
	"tinyint":    Integer,
	"smallint":   Integer,
	"mediumint":  Integer,
	"bigint":     Integer,
	"decimal":    Numeric,
	"numeric":    Numeric,
	"float":      Numeric,
	"double":     Numeric,
	"real":       Numeric,
	"date":       Date,
	"datetime":   DateTime,
	"timestamp":  DateTime,
	"time":       Time,
}

var PgTypeMap = map[string]DbType{
	"int2":      Integer,
	"int4":      Integer,
	"int8":      Integer,
	"smallint":  Integer,
	"integer":   Integer,
	"bigint":    Integer,
	"serial":    Integer,
	"bigserial": Integer,
	"timestamp": DateTime,
	"date":      Date,
	"time":      Time,
	"bool":      Boolean,
	"boolean":   Boolean,
	"varchar":   String,
	"char":      Char,
	"text":      String,
	"numeric":   Numeric,
	"decimal":   Numeric,
	"real":      Numeric,
	"double":    Numeric,
}

var PLSqlTypeMap = map[string]DbType{
	"BINARY_INTEGER":   Integer,
	"PLS_INTEGER":      Integer,
	"NATURAL":          Integer,
	"BINARY_FLOAT":     Numeric,
	"BINARY_DOUBLE":    Numeric,
	"NATURALN":         Integer,
	"POSITIVE":         Integer,
	"POSITIVEN":        Integer,
	"SIGNTYPE":         Integer,
	"NVARCHAR2":        String,
	"DEC":              Numeric,
	"INTEGER":          Integer,
	"INT":              Integer,
	"NUMERIC":          Numeric,
	"SMALLINT":         Integer,
	"NUMBER":           Numeric,
	"DECIMAL":          Numeric,
	"DOUBLE PRECISION": Numeric,
	"DOUBLE":           Numeric,
	"FLOAT":            Numeric,
	"REAL":             Numeric,
	"NCHAR":            Char,
	// "LONG RAW":                       "",
	"CHAR":      Char,
	"CHARACTER": String,
	"VARCHAR2":  String,
	"VARCHAR":   String,
	"STRING":    String,
	"RAW":       "",
	"BOOLEAN":   Boolean,
	"DATE":      Date,
	// "ROWID":                          "",
	// "UROWID":                         "",
	// "YEAR":                           "",
	// "MONTH":                          "",
	// "DAY":                            "",
	// "HOUR":                           "",
	// "MINUTE":                         "",
	// "SECOND":                         "",
	// "TIMEZONE_HOUR":                  "",
	// "TIMEZONE_MINUTE":                "",
	// "TIMEZONE_REGION":                "",
	// "TIMEZONE_ABBR":                  "",
	"TIMESTAMP": DateTime,
	// "TIMESTAMP_UNCONSTRAINED":        "",
	// "TIMESTAMP_TZ_UNCONSTRAINED":     "",
	// "TIMESTAMP_LTZ_UNCONSTRAINED":    "",
	// "YMINTERVAL_UNCONSTRAINED":       "",
	// "DSINTERVAL_UNCONSTRAINED":       "",
	// "BFILE":                          "",
	// "BLOB":                           "",
	// "CLOB":                           "",
	// "NCLOB":                          "",
	// "MLSLABEL":                       "",
	// "XMLTYPE":                        "",
	// "LONG":                           "",
	// "INTERVAL YEAR TO MONTH":         "",
	// "INTERVAL DAY TO SECOND":         "",
	"TIMESTAMP WITH TIME ZONE":       DateTime,
	"TIMESTAMP WITH LOCAL TIME ZONE": DateTime,
}

var HiveTypeMap = map[string]DbType{
	"tinyint":   Integer,
	"smallint":  Integer,
	"int":       Integer,
	"bigint":    Integer,
	"boolean":   Boolean,
	"float":     Numeric,
	"real":      Numeric,
	"double":    Numeric,
	"date":      Date,
	"datetime":  DateTime,
	"timestamp": DateTime,
	// | KW_TIMESTAMPLOCALTZ
	// | KW_TIMESTAMPTZ
	// | KW_TIMESTAMP KW_WITH KW_TIME KW_ZONE
	// | KW_INTERVAL KW_YEAR KW_TO KW_MONTH
	// | KW_INTERVAL KW_DAY KW_TO KW_SECOND
	// | KW_BINARY
	"string":  String,
	"varchar": String,
	"char":    Char,
	"decimal": Numeric,
}

var SqliteTypeMap = map[string]DbType{
	"INT":              Integer,
	"INTEGER":          Integer,
	"TINYINT":          Integer,
	"SMALLINT":         Integer,
	"MEDIUMINT":        Integer,
	"BIGINT":           Integer,
	"UNSIGNEDBIGINT":   Integer,
	"INT2":             Integer,
	"INT8":             Integer,
	"CHARACTER":        String,
	"VARCHAR":          String,
	"VARYINGCHARACTER": String,
	"CHAR":             Char,
	"NCHAR":            Char,
	"NATIVECHARACTER":  String,
	"NVARCHAR":         String,
	"TEXT":             String,
	"CLOB":             String,
	// "BLOB":             "",
	"REAL":            Numeric,
	"DOUBLE":          Numeric,
	"DOUBLEPRECISION": Numeric,
	"FLOAT":           Numeric,
	"NUMERIC":         Numeric,
	"DECIMAL":         Numeric,
	"BOOLEAN":         Boolean,
	"DATE":            Date,
	"DATETIME":        DateTime,
}

var TSqlTypeMap = map[string]DbType{
	"tinyint":    Integer,
	"int":        Integer,
	"bigint":     Integer,
	"smallint":   Integer,
	"bit":        Integer,
	"decimal":    Numeric,
	"numeric":    Numeric,
	"money":      Numeric,
	"smallmoney": Numeric,
	"float":      Numeric,
	"real":       Numeric,
	"date":       Date,
	"time":       Time,
	"datetime2":  DateTime,
	// "datetimeoffset":   "",
	"datetime": DateTime,
	"char":     Char,
	"varchar":  String,
	"text":     String,
	"nchar":    Char,
	"nvarchar": String,
	"ntext":    String,
	// "binary":           "",
	// "varbinary":        "",
	// "image":            "",
	// "cursor":           "",
	// "geography":        "",
	// "geometry":         "",
	// "hierarchyid":      "",
	// "json":             "",
	// "rowversion":       "",
	// "sql_variant":      "",
	// "table":            "",
	// "uniqueidentifier": "",
	// "xml":              "",
}
